name: Training Project Pipeline

on:
  push:
    branches:
      - master

jobs:
  test-and-flag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      

      - name: Run PyTest
        run: pytest -v

      - name: Verify success flag file
        run: |
          if [ ! -f example.txt ]; then
            echo "example.txt not found â€“ CI failed"
            exit 1
          fi

      - name: Upload success flag file
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-proof
          path: example.txt
